{'name': 'Salon Management',
 'version': 'saas~19.4.1.0',
 'category': 'Studio',
 'description': 'This module has been generated by Odoo Studio.\n'
                'It contains the apps created with Studio and the '
                'customizations of existing apps.',
 'author': 'YourCompany',
 'depends': ['account_reports', 'hr', 'hr_skills', 'web_grid', 'web_studio'],
 'data': ['data/ir_model.xml',
          'data/ir_model_fields.xml',
          'data/mail_templates.xml',
          'data/ir_actions_act_window.xml',
          'data/ir_actions_server.xml',
          'data/ir_ui_view.xml',
          'data/ir_ui_menu.xml',
          'data/base_automation.xml',
          'data/ir_access.xml',
          'data/ir_sequence_data.xml',
          'data/ir_default.xml'],
 'demo': ['demo/salon_demo.xml'],
 'assets': {
     'web.assets_backend': [
         'salon_management_saas/static/src/js/salon_dashboard.js',
         'salon_management_saas/static/src/xml/salon_dashboard.xml',
     ]
 },
 'license': 'OPL-1'}